--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ZzKino/EasyWing
build-by-default: true
branches:
- master
projects:
  EasyWing:
    iocn: icon.png
    path: ""
    libs:
    - src: Vecnavium/FormsUI/libFormsUI
      version: ^2.0.0
...
